name: eSocial Automation

on:
  push:
    branches:
      - main
  # Uncomment the schedule block below to run the workflow on a regular schedule.
  # schedule:
  #   - cron: "0 0 * * *"  # runs daily at midnight UTC

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser python3-distutils

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install undetected-chromedriver selenium requests python-dotenv twilio

      - name: Run eSocial automation script
        env:
          ESOCIAL_CPF: ${{ secrets.ESOCIAL_CPF }}
          ESOCIAL_SENHA: ${{ secrets.ESOCIAL_SENHA }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: |
          python main.py



