name: eSocial Automation

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of each month
  push:
    branches:
      - main

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser python3-distutils

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install undetected-chromedriver selenium requests python-dotenv twilio

      - name: Run eSocial automation script
        env:
          ESOCIAL_CPF: ${{ secrets.ESOCIAL_CPF }}
          ESOCIAL_SENHA: ${{ secrets.ESOCIAL_SENHA }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: |
          python main.py




